Add seccomp profile support to PodSecurityContext in Kubernetes for Skuber library
hagay3/skuber pull request #366
Opened 2024-02-27 17:01 UTC by Dream1Master

This pull request adds support for seccomp profiles in Kubernetes PodSecurityContext for the Skuber library. This change is necessary for better security compliance of the Skuber library.

The technical details of this change are as follows:

- Added a new field to the PodSecurityContext struct in Skuber to support seccomp profiles.
- Modified json parser to parse seccompProfile field from PodSecurityContext struct

This change is important because it provides better security compliance for the Skuber library. Seccomp profiles restrict the types of system calls that a container can make, reducing the attack surface of the container and improving overall security.

Information about restrict a Container's Syscalls with seccomp available via link https://kubernetes.io/docs/tutorials/security/seccomp/
Linux seccomp overview available via link https://lwn.net/Articles/656307/

Thank you for your time and attention in reviewing this pull request. Please let me know if you have any questions or concerns.

2024-02-27 17:35 UTC, hagay3 commented on client/src/main/scala/skuber/json/package.scala
> +      case _ => JsError(s"Unknown Seccomp")
please treat the error in a more resilient way, you can return Option[SeccompProfile] and in that case None or you can configure a profile that is "Unknown"

2024-02-27 17:40 UTC, hagay3 requested changes
@Dream1Master 
Thank you for taking the time and contributing to skuber :)

In addition, if you could invest some time and create an integration test for `PodFormat` that would be great.
you can take as an example  `PodFormatSpec` integration test under `it` folder.

2024-02-27 17:40 UTC, hagay3 commented on client/src/main/scala/skuber/json/package.scala
> +          case operator => JsError(s"Unknown Seccomp profile '$operator'")
same

2024-02-28 17:07 UTC, Dream1Master commented on client/src/main/scala/skuber/json/package.scala
> +      case _ => JsError(s"Unknown Seccomp")
replace JsError with "Unknown" profile

2024-02-28 17:07 UTC, Dream1Master commented on client/src/main/scala/skuber/json/package.scala
> +          case operator => JsError(s"Unknown Seccomp profile '$operator'")
replace JsError with "Unknown" profile

2024-02-28 17:21 UTC, Dream1Master commented
> @Dream1Master Thank you for taking the time and contributing to skuber :)
> 
> In addition, if you could invest some time and create an integration test for `PodFormat` that would be great. you can take as an example `PodFormatSpec` integration test under `it` folder.

I have created integration tests for the PodFormatSpec in the format package, located in the `it` folder. I would appreciate it if you could take a moment to review the changes and let me know if they meet your expectations.

2024-02-29 13:02 UTC, hagay3 approved these changes

2024-02-29 14:34 UTC, merged

2024-03-04 12:17 UTC, hagay3 commented
@Dream1Master v4.0.3 has been released with seccomp profile